{"name": "# C5177 Add a new device that has already registered in the system", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1072, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1604157988437, "stop": 1604157991264}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1604157991265, "stop": 1604157994082}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "passed", "start": 1604157994083, "stop": 1604157994267}, {"name": "Then Click Add new device button on the right up corner", "status": "passed", "start": 1604157994268, "stop": 1604157994714}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "passed", "start": 1604157994715, "stop": 1604157994902}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "passed", "start": 1604157994902, "stop": 1604157995087}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "passed", "start": 1604157995088, "stop": 1604157995225}, {"name": "And Click Save and refresh the page", "status": "passed", "start": 1604157995225, "stop": 1604157996452}, {"name": "Then Success is here - device is on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1072, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1604157996453, "stop": 1604158014701}, {"name": "Then Add a new device that has already registered in the system", "status": "skipped", "start": 1604158016821, "stop": 1604158016821}, {"name": "Then The system should check if the device has already registered a prompt should appear Device already exists", "status": "skipped", "start": 1604158016821, "stop": 1604158016821}], "start": 1604157982984, "stop": 1604158016821, "uuid": "5319c138-b67f-4beb-8ca3-ff7c8022162f", "historyId": "b595c97d934ae9dff1c5f5d73f8298ad", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5177 Add a new device that has already registered in the system"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}