{"name": "# C5154_Verify_if_the_\"Inventory\"_card_is_working", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-tbc-c7=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (669, 177). Other element would receive the click: <div _ngcontent-tbc-c6=\"\" class=\"spinner-outer ng-tns-c6-0 ng-star-inserted\">...</div>\n  (Session info: chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5154_Verify_if_the_Inventory_card_is_working.py\", line 8, in clck_on_invntr_elmnt\n    context.app.main_page.clck_on_invntr_elmnt()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 532, in clck_on_invntr_elmnt\n    invntr_elmnt.click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1601146774751, "stop": 1601146777730}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1601146777730, "stop": 1601146783176}, {"name": "Then Click on the INVENTORY card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-tbc-c7=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (669, 177). Other element would receive the click: <div _ngcontent-tbc-c6=\"\" class=\"spinner-outer ng-tns-c6-0 ng-star-inserted\">...</div>\n  (Session info: chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5154_Verify_if_the_Inventory_card_is_working.py\", line 8, in clck_on_invntr_elmnt\n    context.app.main_page.clck_on_invntr_elmnt()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 532, in clck_on_invntr_elmnt\n    invntr_elmnt.click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601146783176, "stop": 1601146784247}, {"name": "And https://devcloud.connectedio.com/devices is open", "status": "skipped", "start": 1601146786385, "stop": 1601146786385}, {"name": "And Inventory status in FILTERS field", "status": "skipped", "start": 1601146786385, "stop": 1601146786385}], "start": 1601146769449, "stop": 1601146786385, "uuid": "bce7fd81-66eb-43cc-a06c-5186fe092a4a", "historyId": "458e42f7bf828a70655edd09995b6c99", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5154_Verify_if_the_\"Inventory\"_card_is_working"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}