{"name": "# C5440 Delete User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 40, in vrf_usr_dltd\n    context.app.main_page.vrf_usr_dltd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 214, in vrf_usr_dltd\n    len_admins = len(wait.until(EC.presence_of_all_elements_located((ADMIN))))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1600401493887, "stop": 1600401496647}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1600401496647, "stop": 1600401498223}, {"name": "Then Click on the Users button", "status": "passed", "start": 1600401498223, "stop": 1600401499935}, {"name": "Then Make sure there are at least two Admins and one User role in the list of users", "status": "passed", "start": 1600401499935, "stop": 1600401500440}, {"name": "Then Click on the Settings 'three vertical' dots from the rightmost side of the user", "status": "passed", "start": 1600401500441, "stop": 1600401500622}, {"name": "Then Choose and click on 'Delete' from the dropdown menu", "status": "passed", "start": 1600401500622, "stop": 1600401500790}, {"name": "Then Confirm action by clicking OK button on the pop-up dialog window", "status": "passed", "start": 1600401500790, "stop": 1600401500992}, {"name": "Then Then Verify that there is for one user less after deleting", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 40, in vrf_usr_dltd\n    context.app.main_page.vrf_usr_dltd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 214, in vrf_usr_dltd\n    len_admins = len(wait.until(EC.presence_of_all_elements_located((ADMIN))))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600401500993, "stop": 1600401520574}], "start": 1600401488567, "stop": 1600401522732, "uuid": "92a342a9-dd51-4032-8e9e-a68ca28aff33", "historyId": "052d21b30082a18d0bb410aa5def4f94", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5440 Delete User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}