{"name": "# C5440 Delete User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 40, in vrf_usr_dltd\n    context.app.main_page.vrf_usr_dltd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 217, in vrf_usr_dltd\n    len_admins = len(wait.until(EC.presence_of_all_elements_located((ADMIN))))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1600648738116, "stop": 1600648741145}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1600648741145, "stop": 1600648746776}, {"name": "Then Click on the Users button", "status": "passed", "start": 1600648746776, "stop": 1600648746923}, {"name": "Then Make sure there are at least two Admins and one User role in the list of users", "status": "passed", "start": 1600648746924, "stop": 1600648747233}, {"name": "Then Click on the Settings 'three vertical' dots from the rightmost side of the user", "status": "passed", "start": 1600648747233, "stop": 1600648747303}, {"name": "Then Choose and click on 'Delete' from the dropdown menu", "status": "passed", "start": 1600648747303, "stop": 1600648747394}, {"name": "Then Confirm action by clicking OK button on the pop-up dialog window", "status": "passed", "start": 1600648747395, "stop": 1600648747516}, {"name": "Then Then Verify that there is for one user less after deleting", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 40, in vrf_usr_dltd\n    context.app.main_page.vrf_usr_dltd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 217, in vrf_usr_dltd\n    len_admins = len(wait.until(EC.presence_of_all_elements_located((ADMIN))))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600648747516, "stop": 1600648766551}], "start": 1600648732814, "stop": 1600648768665, "uuid": "186cec63-49df-4c65-8f19-ec9124bd666f", "historyId": "052d21b30082a18d0bb410aa5def4f94", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5440 Delete User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}