{"name": "# C5152 Verify if the Device offline card is working", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-usl-c7=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (539, 177). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.111)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 564, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1604100564483, "stop": 1604100567496}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1604100567497, "stop": 1604100570347}, {"name": "Then Click on DEVICE OFFLINE card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-usl-c7=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (539, 177). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.111)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 564, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1604100570347, "stop": 1604100571570}, {"name": "And https://devcloud.connectedio.com/devices is open", "status": "skipped", "start": 1604100573667, "stop": 1604100573667}, {"name": "Then Verify Offline status in FILTERS field is seen", "status": "skipped", "start": 1604100573667, "stop": 1604100573667}], "start": 1604100559045, "stop": 1604100573667, "uuid": "16abd34e-b6ac-425e-a653-98209c14edac", "historyId": "eb7d915b408c8a8ca953391c2e2f18e1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5152 Verify if the Device offline card is working"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}