{"name": "# C5121 Logout from_the_Header and verify the login page will open after logout", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UI_automation_python_connectedIO\\pages\\main_page.py\", line 173, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1624124913754, "stop": 1624124917690}, {"name": "Then Login with the given credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UI_automation_python_connectedIO\\pages\\main_page.py\", line 173, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1624124917691, "stop": 1624124931763}, {"name": "Then Hover over the Logout button at the right corner of the Header and click on the button Logout", "status": "skipped", "start": 1624124933901, "stop": 1624124933901}, {"name": "And https://devcloud.connectedio.com/ is open", "status": "skipped", "start": 1624124933901, "stop": 1624124933901}], "start": 1624124911881, "stop": 1624124933901, "uuid": "04d10fe1-b77b-49b7-aa57-33c851e62b0b", "historyId": "5195210d41c1c882304aa237be7bc9a5", "fullName": "# C5121 Logout from_the_Header: # C5121 Logout from_the_Header and verify the login page will open after logout", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5121 Logout from_the_Header"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}