{"name": "# C5176 Add a new device", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1075, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1606530287396, "stop": 1606530290465}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1606530290465, "stop": 1606530293437}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "passed", "start": 1606530293438, "stop": 1606530293802}, {"name": "Then Click Add new device button on the right up corner", "status": "passed", "start": 1606530293802, "stop": 1606530294353}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "passed", "start": 1606530294354, "stop": 1606530294593}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "passed", "start": 1606530294593, "stop": 1606530294863}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "passed", "start": 1606530294863, "stop": 1606530295055}, {"name": "And Click Save and refresh the page", "status": "passed", "start": 1606530295055, "stop": 1606530296853}, {"name": "Then Success is here - device is on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1075, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1606530296854, "stop": 1606530315001}, {"name": "Then Delete device", "status": "skipped", "start": 1606530317119, "stop": 1606530317119}], "start": 1606530282162, "stop": 1606530317119, "uuid": "94a7c0d2-41e7-4aee-8f5e-d8d7a710e1c8", "historyId": "f66297f0cc4ca767f9caf1684373e3ca", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5176 Add a new device"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}