{"name": "# C5159 Data Usage details section", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a _ngcontent-yet-c5=\"\" ng-reflect-router-link=\"/\" href=\"/\" class=\"ng-star-inserted\">...</a> is not clickable at point (122, 236). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=87.0.4280.66)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5159_Data_Usage_details_section.py\", line 8, in clck_on_dsch_brd_mn_icn\n    context.app.main_page.clck_on_dsch_brd_mn_icn(dsbrd_txt)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 689, in clck_on_dsch_brd_mn_icn\n    wait.until(EC.visibility_of_element_located(DSCH_BRD_ICN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1606886235963, "stop": 1606886241550}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1606886241551, "stop": 1606886244501}, {"name": "Then Click Dashboard menu icon and make sure Dashboard page reloaded", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a _ngcontent-yet-c5=\"\" ng-reflect-router-link=\"/\" href=\"/\" class=\"ng-star-inserted\">...</a> is not clickable at point (122, 236). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=87.0.4280.66)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5159_Data_Usage_details_section.py\", line 8, in clck_on_dsch_brd_mn_icn\n    context.app.main_page.clck_on_dsch_brd_mn_icn(dsbrd_txt)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 689, in clck_on_dsch_brd_mn_icn\n    wait.until(EC.visibility_of_element_located(DSCH_BRD_ICN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1606886244501, "stop": 1606886245580}, {"name": "Then Make sure Data Usage Details block DATA USAGE is present on the screen", "status": "skipped", "start": 1606886247658, "stop": 1606886247658}, {"name": "And Hover over question mark in top right of the block and make sure tooltip WAN/Cellular data usage classified periodically. appears", "status": "skipped", "start": 1606886247658, "stop": 1606886247658}, {"name": "And Change in drop-down changes the columns = click on Today option from drop-down menu", "status": "skipped", "start": 1606886247658, "stop": 1606886247658}, {"name": "Then The inscription No Data Available is in the center", "status": "skipped", "start": 1606886247658, "stop": 1606886247658}, {"name": "Then Verify GB inactive column highlighted grey 128, 128, 128, 1 when hover over it and hold", "status": "skipped", "start": 1606886247658, "stop": 1606886247658}], "start": 1606886230793, "stop": 1606886247658, "uuid": "1d72b03f-d03e-484e-a50c-d2f16475da55", "historyId": "9c862706ba996091f8c9c28ea831b944", "fullName": "features/tests/Dashboard/C5159_Data_Usage_details_section.feature:# C5159 Data Usage details section", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5159 Data Usage details section"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}