{"name": "# C5177 Add a new device that has already registered in the system", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <i _ngcontent-osg-c5=\"\" class=\"fa fa-hdd-o\"></i> is not clickable at point (30, 300). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.75)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 8, in go_to_dvcs_pg\n    context.app.main_page.go_to_dvcs_pg(dvcs_url)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1004, in go_to_dvcs_pg\n    wait.until(EC.element_to_be_clickable(DVCS_ICN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1602122254117, "stop": 1602122257170}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1602122257170, "stop": 1602122259982}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <i _ngcontent-osg-c5=\"\" class=\"fa fa-hdd-o\"></i> is not clickable at point (30, 300). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.75)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 8, in go_to_dvcs_pg\n    context.app.main_page.go_to_dvcs_pg(dvcs_url)\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1004, in go_to_dvcs_pg\n    wait.until(EC.element_to_be_clickable(DVCS_ICN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1602122259982, "stop": 1602122261128}, {"name": "Then Click Add new device button on the right up corner", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "And Click Save and refresh the page", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "Then Success is here - device is on the page", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "Then Add a new device that has already registered in the system", "status": "skipped", "start": 1602122263238, "stop": 1602122263238}, {"name": "Then The system should check if the device has already registered a prompt should appear Device already exists", "status": "skipped", "start": 1602122263239, "stop": 1602122263239}], "start": 1602122248687, "stop": 1602122263239, "uuid": "e1152752-ed4c-4ca5-8dad-4d6e783d11f9", "historyId": "b595c97d934ae9dff1c5f5d73f8298ad", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5177 Add a new device that has already registered in the system"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}