{"name": "# C5152 Verify if the Device offline card is working", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-mik-c8=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (553, 177). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.183)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 568, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1604877951272, "stop": 1604877954075}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1604877954075, "stop": 1604877956922}, {"name": "Then Click on DEVICE OFFLINE card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-mik-c8=\"\" class=\"card overflowhidden number-chart d-flex flex-column\">...</div> is not clickable at point (553, 177). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=86.0.4240.183)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 568, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1604877956922, "stop": 1604877958049}, {"name": "And https://devcloud.connectedio.com/devices is open", "status": "skipped", "start": 1604877960166, "stop": 1604877960166}, {"name": "Then Verify Offline status in FILTERS field is seen", "status": "skipped", "start": 1604877960166, "stop": 1604877960166}], "start": 1604877945864, "stop": 1604877960166, "uuid": "04422968-a313-40fa-a1e4-f4e1e64c4dbe", "historyId": "eb7d915b408c8a8ca953391c2e2f18e1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5152 Verify if the Device offline card is working"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}