{"name": "# C5472 Add New User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 91, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1601147989325, "stop": 1601147991992}, {"name": "Then Login with the given credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 91, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1601147991992, "stop": 1601148005912}, {"name": "Then Click on the Users button", "status": "skipped", "start": 1601148008045, "stop": 1601148008046}, {"name": "Then Click on the Quick actions button", "status": "skipped", "start": 1601148008046, "stop": 1601148008046}, {"name": "Then Select Add in the drop-down menu", "status": "skipped", "start": 1601148008046, "stop": 1601148008046}, {"name": "Then Fill out the required fields", "status": "skipped", "start": 1601148008046, "stop": 1601148008046}, {"name": "And Click on the Add button", "status": "skipped", "start": 1601148008046, "stop": 1601148008046}, {"name": "Then Verify the words Verification Pending is here", "status": "skipped", "start": 1601148008046, "stop": 1601148008046}], "start": 1601147984047, "stop": 1601148008046, "uuid": "f7270822-0642-4e20-8321-efca6bd401c7", "historyId": "9e5459a23f71aa5ecb178366876d40a3", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5472 Add New User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}