{"name": "# C5156 Verify if the Alert Notification card is working", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-gqo-c6=\"\" class=\"body information-card\">...</div> is not clickable at point (952, 173). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5156_Verify_if_the_Alert_Notification_card_is_working.py\", line 8, in clck_on_alrt_ntfctn_crd\n    context.app.main_page.clck_on_alrt_ntfctn_crd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 631, in clck_on_alrt_ntfctn_crd\n    (wait.until(EC.element_to_be_clickable(ALRT_VRFCTN_CRT))).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1602038357481, "stop": 1602038360519}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1602038360520, "stop": 1602038363340}, {"name": "Then Click on ALERT/NOTIFICATION card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div _ngcontent-gqo-c6=\"\" class=\"body information-card\">...</div> is not clickable at point (952, 173). Other element would receive the click: <div class=\"swal2-container swal2-center swal2-fade swal2-shown\" style=\"overflow-y: hidden;\">...</div>\n  (Session info: chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5156_Verify_if_the_Alert_Notification_card_is_working.py\", line 8, in clck_on_alrt_ntfctn_crd\n    context.app.main_page.clck_on_alrt_ntfctn_crd()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 631, in clck_on_alrt_ntfctn_crd\n    (wait.until(EC.element_to_be_clickable(ALRT_VRFCTN_CRT))).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1602038363341, "stop": 1602038364439}, {"name": "Then Verify Alert Dashboard words on the page", "status": "skipped", "start": 1602038366553, "stop": 1602038366553}, {"name": "And https://devcloud.connectedio.com/alerts is open", "status": "skipped", "start": 1602038366553, "stop": 1602038366553}], "start": 1602038352157, "stop": 1602038366553, "uuid": "4580d546-2b8f-48a5-ae27-73ad82d23325", "historyId": "b2406d5d6418f72e7ecb6f0c11c58d76", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5156 Verify if the Alert Notification card is working"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}